# use "bundle install" to update gems; "gem install bundler" to install bundler.
source :rubygems
source "http://gems.local.twitter.com"
gem "thrift_client", "0.9.3"
gem "thrift", "0.9.1"
gem "railsless-deploy"
gem "capistrano"
